<?php

use Illuminate\Database\Seeder;

class areaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('areas')->insert([

['name' => "Mohammadpur মোহাম্মদপুর", 'zone_id' => 1],
['name' => "Dhanmondi ধানমন্ডি", 'zone_id' => 1],
['name' => "Gulshan গুলশান", 'zone_id' => 1],
['name' => "Kallyanpur কল্যাণপুর", 'zone_id' => 1],
['name' => "Shyamoli শ্যামলী", 'zone_id' => 1],
['name' => "Adabor আদাবর", 'zone_id' => 1],
['name' => "Darussalam দারুসসালাম", 'zone_id' => 1],
['name' => "Gabtoli গাবতলী", 'zone_id' => 1],
['name' => "Pallabi পল্লবী", 'zone_id' => 1],
['name' => "Lalmatia লালমাটিয়া", 'zone_id' => 1],
['name' => "Mirpur DOHS মিরপুর ডিওএইচএস", 'zone_id' => 1],
['name' => "Kochukhet কচুখেত", 'zone_id' => 1],
['name' => "Gudaraghat গুদারাঘাট", 'zone_id' => 1],
['name' => "Agargaon আগারগাও", 'zone_id' => 1],
['name' => "Monipur মণিপুর", 'zone_id' => 1],
['name' => "Sher-E-Bangla Nagar শের-এ-বাংলা নগর", 'zone_id' => 1],
['name' => "Ibrahimpur ইব্রাহীমপুর", 'zone_id' => 1],
['name' => "Dhaka Cantonment ঢাকা ক্যান্টনমেন্ট", 'zone_id' => 1],
['name' => "Mirpur Cantonment মিরপুর ক্যান্টনমেন্ট", 'zone_id' => 1],
['name' => "Kafrul কাফরুল", 'zone_id' => 1],
['name' => "Vashantek ভাসানটেক", 'zone_id' => 1],
['name' => "Manikdi মানিকদি", 'zone_id' => 1],
['name' => "Matikata মাটিকাটা", 'zone_id' => 1],
['name' => "M.E.S এম.ই.এস", 'zone_id' => 1],
['name' => "Rupnagar Residential Area", 'zone_id' => 1],
['name' => "Duaripara", 'zone_id' => 1],
['name' => "Rainkhola", 'zone_id' => 1],
['name' => "Mirpur Diabari", 'zone_id' => 1],
['name' => "Mazar Road", 'zone_id' => 1],
['name' => "Shagufta", 'zone_id' => 1],
['name' => "Bawnia", 'zone_id' => 1],
['name' => "Baigertek", 'zone_id' => 1],
['name' => "Madina nagar", 'zone_id' => 1],
['name' => "Dewanpara", 'zone_id' => 1],
['name' => "Namapara", 'zone_id' => 1],
['name' => "Mastertek", 'zone_id' => 1],
['name' => "Balughat", 'zone_id' => 1],
['name' => "Barontek", 'zone_id' => 1],
['name' => "Goltek", 'zone_id' => 1],
['name' => "Kurmitola", 'zone_id' => 1],
['name' => "Shewra", 'zone_id' => 1],
['name' => "Uttara উত্তরা", 'zone_id' => 1],
['name' => "Uttarkhan উত্তরখান", 'zone_id' => 1],
['name' => "Dakshinkhan দক্ষিণখান", 'zone_id' => 1],
['name' => "Fayedabad", 'zone_id' => 1],
['name' => "Ashkona আশকোনা", 'zone_id' => 1],
['name' => "Kuril কুড়িল", 'zone_id' => 1],
['name' => "Savar সাভার", 'zone_id' => 1],
['name' => false, 'zone_id' => 1],
['name' => "Khilkhet খিলখেত", 'zone_id' => 1],
['name' => "Nikunja নিকুঞ্জ", 'zone_id' => 1],
['name' => "Azampur আজমপুর", 'zone_id' => 1],
['name' => "Hajipara হাজীপাড়া", 'zone_id' => 1],
['name' => "Kawla কাওলা", 'zone_id' => 1],
['name' => "Naddapara নদ্দাপারা", 'zone_id' => 1],
['name' => "Bashundhara R/A বাসুন্ধরা আবাসিক এলাকা", 'zone_id' => 1],
['name' => "Vatara ভাটারা", 'zone_id' => 1],
['name' => "Nadda নদ্দা", 'zone_id' => 1],
['name' => "Baridhara বারিধারা", 'zone_id' => 1],
['name' => "Baridhara DOHS বারিধারা ডিওএইচএস", 'zone_id' => 1],
['name' => "Notun Bazar নতুন বাজার", 'zone_id' => 1],
['name' => "Badda বাড্ডা", 'zone_id' => 1],
['name' => "Shahjadpur শাহজাদপুর", 'zone_id' => 1],
['name' => "Uttor Badda উত্তর বাড্ডা", 'zone_id' => 1],
['name' => "Middle Badda মধ্য বাড্ডা", 'zone_id' => 1],
['name' => "South Badda দক্ষিণ বাড্ডা", 'zone_id' => 1],
['name' => "Merul Badda মেরুল বাড্ডা", 'zone_id' => 1],
['name' => "Niketon নিকেতন", 'zone_id' => 1],
['name' => "Banani বনানী", 'zone_id' => 1],
['name' => "Banani DOHS বনানী ডিওএইচএস", 'zone_id' => 1],
['name' => "Mohakhali মহাখালী", 'zone_id' => 1],
['name' => "Mohakhali DOHS মহাখালী ডিওএইচএস", 'zone_id' => 1],
['name' => "South Monipur দক্ষিণ মনিপুর", 'zone_id' => 1],
['name' => "Shah Ali Bag শাহ আলী বাগ", 'zone_id' => 1],
['name' => "Aziz Palli আজিজ পল্লী", 'zone_id' => 1],
['name' => "Bashtola বাঁশতলা", 'zone_id' => 1],
['name' => "South Baridhara, DIT Project দক্ষিণ বারিধারা, ডিআইটি প্রোজেক্ট", 'zone_id' => 1],
['name' => "Aftabnagar আফতাবনগর", 'zone_id' => 1],
['name' => "Bijoy Shoroni বিজয়স্মরনি", 'zone_id' => 1],
['name' => "Farmgate ফার্মগেট", 'zone_id' => 1],
['name' => "Indira Road ইন্দিরারোড", 'zone_id' => 1],
['name' => "Tejgaon তেজগাঁও", 'zone_id' => 1],
['name' => "Tejkunipara তেজকুনিপারা", 'zone_id' => 1],
['name' => "Razabazar রাজাবাজার", 'zone_id' => 1],
['name' => "Sukrabad সুক্রাবাদ", 'zone_id' => 1],
['name' => "Panthopath পান্থপথ", 'zone_id' => 1],
['name' => "Kalabagan কলাবাগান", 'zone_id' => 1],
['name' => "Green Road গ্রীনরোড", 'zone_id' => 1],
['name' => "Manik Mia Avenue মানিক মিয়া এভিনিউ", 'zone_id' => 1],
['name' => "Asad Avenue আসাদ এভিনিউ", 'zone_id' => 1],
['name' => "West Dhanmondi পশ্চিম ধানমন্ডি", 'zone_id' => 1],
['name' => "Shankar সংকর", 'zone_id' => 1],
['name' => "Rayer Bazar রায়েরবাজার", 'zone_id' => 1],
['name' => "Tallabag তাল্লাবাগ", 'zone_id' => 1],
['name' => "Hazaribag হাজারীবাগ", 'zone_id' => 1],
['name' => "Pilkhana পিলখানা", 'zone_id' => 1],
['name' => "Nawabgonj puran dhaka নাওয়াবগজ", 'zone_id' => 1],
['name' => "New Market নিউ মার্কেট", 'zone_id' => 1],
['name' => "Azimpur আজিমপুর", 'zone_id' => 1],
['name' => "Nilkhet নীলক্ষেত", 'zone_id' => 1],
['name' => "Lalbagh লালবাগ", 'zone_id' => 1],
['name' => "Chawkbazar চকবাজার", 'zone_id' => 1],
['name' => "Naya Bazar নয়াবাজার", 'zone_id' => 1],
['name' => "Tatibazar তাঁতিবাজার", 'zone_id' => 1],
['name' => "Luxmi Bazar লক্ষ্মীবাজার", 'zone_id' => 1],
['name' => "puran Dhaka পুরাণ ঢাকা", 'zone_id' => 1],
['name' => "Siddique Bazar সিদ্দিকবাজার", 'zone_id' => 1],
['name' => "Tikatuly টিকাটুলি", 'zone_id' => 1],
['name' => "Motijheel মতিঝিল", 'zone_id' => 1],
['name' => "Nawabpur নওয়াবপুর", 'zone_id' => 1],
['name' => "Kaptan Bazar কাপ্তানবাজার", 'zone_id' => 1],
['name' => "Gulistan গুলিস্তান", 'zone_id' => 1],
['name' => "Bongo Bazar বঙ্গবাজার", 'zone_id' => 1],
['name' => "Chankarpul চাঙ্কারপুল", 'zone_id' => 1],
['name' => "Palashi পলাশী", 'zone_id' => 1],
['name' => "Dhakeshwari ঢাকেশ্বরী", 'zone_id' => 1],
['name' => "Kamalapur", 'zone_id' => 1],
['name' => "Wari ওয়ারী", 'zone_id' => 1],
['name' => "Narinda", 'zone_id' => 1],
['name' => "Dainik Bangla Mor", 'zone_id' => 1],
['name' => "Fakirapul", 'zone_id' => 1],
['name' => "Kakrail", 'zone_id' => 1],
['name' => "Naya Paltan", 'zone_id' => 1],
['name' => "Bijoynagar", 'zone_id' => 1],
['name' => "Press Club", 'zone_id' => 1],
['name' => "High Court", 'zone_id' => 1],
['name' => "Dhaka University", 'zone_id' => 1],
['name' => "Dhaka Medical", 'zone_id' => 1],
['name' => "Bongo Bondhu Avenue", 'zone_id' => 1],
['name' => "Kazi Nazrul Islam Avenue", 'zone_id' => 1],
['name' => "Kawran Bazar", 'zone_id' => 1],
['name' => "Ramna", 'zone_id' => 1],
['name' => "Shantinagar", 'zone_id' => 1],
['name' => "Shantibag", 'zone_id' => 1],
['name' => "Baily Road", 'zone_id' => 1],
['name' => "Minto Road", 'zone_id' => 1],
['name' => "Old Elephant Road", 'zone_id' => 1],
['name' => "Eskaton Garden Road", 'zone_id' => 1],
['name' => "Eskaton", 'zone_id' => 1],
['name' => "Moghbazar", 'zone_id' => 1],
['name' => "Mouchak", 'zone_id' => 1],
['name' => "Malibag", 'zone_id' => 1],
['name' => "Rampura রামপুরা", 'zone_id' => 1],
['name' => "Shahbag শাহবাগ", 'zone_id' => 1],
['name' => "Katabon", 'zone_id' => 1],
['name' => "Hatirpool", 'zone_id' => 1],
['name' => "Bashabo", 'zone_id' => 1],
['name' => "Khilgaon", 'zone_id' => 1],
['name' => "Middle Bashabo", 'zone_id' => 1],
['name' => "Goran", 'zone_id' => 1],
['name' => "Madartek", 'zone_id' => 1],
['name' => "Manik Nagar মানিকনগর", 'zone_id' => 1],
['name' => "Shahjahanpur", 'zone_id' => 1],
['name' => "Banasree", 'zone_id' => 1],
['name' => "Meradia", 'zone_id' => 1],
['name' => "Khilbari Tek", 'zone_id' => 1],
['name' => "Bawaliapara", 'zone_id' => 1],
['name' => "Mughdapara", 'zone_id' => 1],
['name' => "Golapbag", 'zone_id' => 1],
['name' => "Jatrabari", 'zone_id' => 1],
['name' => "Hatirjheel", 'zone_id' => 1],
['name' => "Banglamotor", 'zone_id' => 1],
['name' => "Paribag", 'zone_id' => 1],
['name' => "Bakshibazar বকশিবাজার", 'zone_id' => 1],
['name' => "Elephant Road", 'zone_id' => 1],
['name' => "Kathalbagan", 'zone_id' => 1],
['name' => "Malibagh Taltola", 'zone_id' => 1],
['name' => "Central Road", 'zone_id' => 1],
['name' => "Sabujbag সবুজবাগ", 'zone_id' => 1],
['name' => "Shiddheswari সিদ্ধেশ্বরী", 'zone_id' => 1],
['name' => "Dolaikhal দোলাইখাল", 'zone_id' => 1],
['name' => "Shegunbagicha শেগুনবাগিচা", 'zone_id' => 1],
['name' => "Rajarbag রাজারবাগ", 'zone_id' => 1],
['name' => "Babubazar", 'zone_id' => 1],
['name' => "Islampur", 'zone_id' => 1],
['name' => "Imamgonj", 'zone_id' => 1],
['name' => "Nayabazar নয়াবাজার", 'zone_id' => 1],
['name' => "Zigatola", 'zone_id' => 1],
['name' => "Kazipara", 'zone_id' => 1],
['name' => "Shewrapara", 'zone_id' => 1],
['name' => "Kalshi", 'zone_id' => 1],
['name' => "Sutrapur সূত্রাপুর", 'zone_id' => 1],
['name' => "Purana Paltan পুরানা পল্টন", 'zone_id' => 1],
['name' => "Shyampur শ্যামপুর", 'zone_id' => 1],
['name' => "Dholaipar", 'zone_id' => 1],
['name' => "Monipuripara মনিপুরীপারা", 'zone_id' => 1],
['name' => "Bosila", 'zone_id' => 1],
['name' => "Shonir Akhra শনির আখড়া", 'zone_id' => 1],
['name' => "Mirpur", 'zone_id' => 1],
['name' => "Bongshal", 'zone_id' => 1],
['name' => "Siddweswari", 'zone_id' => 1],
['name' => "Nakhalpara", 'zone_id' => 1],
['name' => "Dokshingaon", 'zone_id' => 1],
['name' => "Joar Shahara", 'zone_id' => 1],
['name' => "Science Lab", 'zone_id' => 1],
['name' => "Sobhanbag", 'zone_id' => 1],
['name' => "ECB Chattar", 'zone_id' => 1],
['name' => "Arambag", 'zone_id' => 1],
['name' => "Armanitola", 'zone_id' => 1],
['name' => "Islambag", 'zone_id' => 1],
['name' => "Kamarpara", 'zone_id' => 1],
['name' => "Mitford", 'zone_id' => 1],
['name' => "Shakhari Bazar", 'zone_id' => 1],
['name' => "Katherpol", 'zone_id' => 1],
['name' => "Bangla Bazar", 'zone_id' => 1],
['name' => "Patuatuly", 'zone_id' => 1],
['name' => "Nandipara", 'zone_id' => 1],
['name' => "Nazira Bazar", 'zone_id' => 1],
['name' => "Gopibag", 'zone_id' => 1],
['name' => "Shwamibag", 'zone_id' => 1],
['name' => "Sayedabad", 'zone_id' => 1],
['name' => "Sadarghat", 'zone_id' => 1],
['name' => "Kaltabazar", 'zone_id' => 1],
['name' => "Jurain", 'zone_id' => 1],
['name' => "Gandaria", 'zone_id' => 1],
['name' => "RayerBag", 'zone_id' => 1],
['name' => "Faridabad", 'zone_id' => 1],
['name' => "Matuail", 'zone_id' => 1],
['name' => "Donia", 'zone_id' => 1],
['name' => "Postogola", 'zone_id' => 1],
['name' => "Konapara", 'zone_id' => 1],
['name' => "Dhaka Uddyan", 'zone_id' => 1],
['name' => "Shekhertek", 'zone_id' => 1],
['name' => "", 'zone_id' => 1],
['name' => "CWH", 'zone_id' => 1],
['name' => "Mirpur Taltola", 'zone_id' => 1],
['name' => "Manda মান্ডা", 'zone_id' => 1],


[ 'name' => "Savar Cantonment সাভার ক্যান্টনমেন্ট", 'zone_id' => 2],
[ 'name' => "Tongi টঙ্গী", 'zone_id' => 2],
[ 'name' => "Demra ডেমরা", 'zone_id' => 2],
[ 'name' => "Ashulia আশুলিয়া", 'zone_id' => 2],
[ 'name' => "Amin Bazar আমিন বাজার", 'zone_id' => 2],
[ 'name' => "Kamrangichar Kamrangichar", 'zone_id' => 2],
[ 'name' => "Keranigonj", 'zone_id' => 2],
[ 'name' => "Dohar", 'zone_id' => 2],
[ 'name' => "Dhamrai", 'zone_id' => 2],
[ 'name' => "Nawabgonj", 'zone_id' => 2],
[ 'name' => "Gazipur Sadar", 'zone_id' => 2],
[ 'name' => "Narayanganj Sadar", 'zone_id' => 2],
[ 'name' => "Siddhirganj সিদ্ধিরগঞ্জ", 'zone_id' => 2],
[ 'name' => "Fatullah ফতুল্লা", 'zone_id' => 2],
[ 'name' => "Kalatia কলাতিয়া", 'zone_id' => 2],
[ 'name' => "Baipayl বাইপাইল", 'zone_id' => 2],


[ 'name' => "Alfadanga", 'zone_id' => 3 ],
[ 'name' => "Bhanga", 'zone_id' => 3 ],
[ 'name' => "Boalmari", 'zone_id' => 3 ],
[ 'name' => "Char Bhadrasan", 'zone_id' => 3 ],
[ 'name' => "Faridpur Sadar", 'zone_id' => 3 ],
[ 'name' => "Madhukhali", 'zone_id' => 3 ],
[ 'name' => "Nagarkanda", 'zone_id' => 3 ],
[ 'name' => "Sadarpur", 'zone_id' => 3 ],
[ 'name' => "Saltha", 'zone_id' => 3 ],
[ 'name' => "Kaliakoir", 'zone_id' => 3 ],
[ 'name' => "Kaliganj", 'zone_id' => 3 ],
[ 'name' => "Kapasia", 'zone_id' => 3 ],
[ 'name' => "Sreepur", 'zone_id' => 3 ],
[ 'name' => "Gopalganj Sadar", 'zone_id' => 3 ],
[ 'name' => "Kasiani", 'zone_id' => 3 ],
[ 'name' => "Kotalipara", 'zone_id' => 3 ],
[ 'name' => "Maksudpur", 'zone_id' => 3 ],
[ 'name' => "Tungipara", 'zone_id' => 3 ],
[ 'name' => "Bakshiganj", 'zone_id' => 3 ],
[ 'name' => "Dewanganj", 'zone_id' => 3 ],
[ 'name' => "Islampur", 'zone_id' => 3 ],
[ 'name' => "Jamalpur Sadar", 'zone_id' => 3 ],
[ 'name' => "Madarganj", 'zone_id' => 3 ],
[ 'name' => "Melandah", 'zone_id' => 3 ],
[ 'name' => "Sharishabari", 'zone_id' => 3 ],
[ 'name' => "Austogram", 'zone_id' => 3 ],
[ 'name' => "Bajitpur", 'zone_id' => 3 ],
[ 'name' => "Bhairab", 'zone_id' => 3 ],
[ 'name' => "Hosainpur", 'zone_id' => 3 ],
[ 'name' => "Itna", 'zone_id' => 3 ],
[ 'name' => "Karimganj", 'zone_id' => 3 ],
[ 'name' => "Katiadi", 'zone_id' => 3 ],
[ 'name' => "Kishoreganj Sadar", 'zone_id' => 3 ],
[ 'name' => "Kuliarchar", 'zone_id' => 3 ],
[ 'name' => "Mithamain", 'zone_id' => 3 ],
[ 'name' => "Nikli", 'zone_id' => 3 ],
[ 'name' => "Pakundia", 'zone_id' => 3 ],
[ 'name' => "Tarail", 'zone_id' => 3 ],
[ 'name' => "Kalkini", 'zone_id' => 3 ],
[ 'name' => "Madaripur Sadar", 'zone_id' => 3 ],
[ 'name' => "Rajoir", 'zone_id' => 3 ],
[ 'name' => "Shibchar", 'zone_id' => 3 ],
[ 'name' => "Daulatpur", 'zone_id' => 3 ],
[ 'name' => "Ghior", 'zone_id' => 3 ],
[ 'name' => "Harirampur", 'zone_id' => 3 ],
[ 'name' => "Manikganj Sadar", 'zone_id' => 3 ],
[ 'name' => "Saturia", 'zone_id' => 3 ],
[ 'name' => "Shibalaya", 'zone_id' => 3 ],
[ 'name' => "Singair", 'zone_id' => 3 ],
[ 'name' => "Gazaria", 'zone_id' => 3 ],
[ 'name' => "Lauhajang", 'zone_id' => 3 ],
[ 'name' => "Munshiganj Sadar", 'zone_id' => 3 ],
[ 'name' => "Serajdikhan", 'zone_id' => 3 ],
[ 'name' => "Sreenagar", 'zone_id' => 3 ],
[ 'name' => "Tangibari", 'zone_id' => 3 ],
[ 'name' => "Bhaluka", 'zone_id' => 3 ],
[ 'name' => "Dhubaura", 'zone_id' => 3 ],
[ 'name' => "Fulbaria", 'zone_id' => 3 ],
[ 'name' => "Fulpur", 'zone_id' => 3 ],
[ 'name' => "Goffargaon", 'zone_id' => 3 ],
[ 'name' => "Gouripur", 'zone_id' => 3 ],
[ 'name' => "Haluaghat", 'zone_id' => 3 ],
[ 'name' => "Iswarganj", 'zone_id' => 3 ],
[ 'name' => "Mymensingh Sadar", 'zone_id' => 3 ],
[ 'name' => "Muktagacha", 'zone_id' => 3 ],
[ 'name' => "Nandail", 'zone_id' => 3 ],
[ 'name' => "Trishal", 'zone_id' => 3 ],
[ 'name' => "Araihazar", 'zone_id' => 3 ],
[ 'name' => "Bandar", 'zone_id' => 3 ],
[ 'name' => "Rupganj", 'zone_id' => 3 ],
[ 'name' => "Sonargaon", 'zone_id' => 3 ],
[ 'name' => "Belabo", 'zone_id' => 3 ],
[ 'name' => "Monohardi", 'zone_id' => 3 ],
[ 'name' => "Norshingdi Sadar", 'zone_id' => 3 ],
[ 'name' => "Palash", 'zone_id' => 3 ],
[ 'name' => "Raipura", 'zone_id' => 3 ],
[ 'name' => "Shibpur", 'zone_id' => 3 ],
[ 'name' => "Atpara", 'zone_id' => 3 ],
[ 'name' => "Barhatta", 'zone_id' => 3 ],
[ 'name' => "Durgapur", 'zone_id' => 3 ],
[ 'name' => "Kalmakanda", 'zone_id' => 3 ],
[ 'name' => "Kendua", 'zone_id' => 3 ],
[ 'name' => "Khaliajuri", 'zone_id' => 3 ],
[ 'name' => "Madan", 'zone_id' => 3 ],
[ 'name' => "Mohanganj", 'zone_id' => 3 ],
[ 'name' => "Netrokona Sadar", 'zone_id' => 3 ],
[ 'name' => "Purbadhala", 'zone_id' => 3 ],
[ 'name' => "Baliakandi", 'zone_id' => 3 ],
[ 'name' => "Goalunda", 'zone_id' => 3 ],
[ 'name' => "Pangsha", 'zone_id' => 3 ],
[ 'name' => "Rajbari Sadar", 'zone_id' => 3 ],
[ 'name' => "Kalukhale", 'zone_id' => 3 ],
[ 'name' => "Bhedarganj", 'zone_id' => 3 ],
[ 'name' => "Damudiya", 'zone_id' => 3 ],
[ 'name' => "Gosairhat", 'zone_id' => 3 ],
[ 'name' => "Zajira", 'zone_id' => 3 ],
[ 'name' => "Naria", 'zone_id' => 3 ],
[ 'name' => "Shariatpur Sadar", 'zone_id' => 3 ],
[ 'name' => "Jhenaigati", 'zone_id' => 3 ],
[ 'name' => "Nakla", 'zone_id' => 3 ],
[ 'name' => "Nalitabari", 'zone_id' => 3 ],
[ 'name' => "Sherpur Sadar", 'zone_id' => 3 ],
[ 'name' => "Sribordi", 'zone_id' => 3 ],
[ 'name' => "Bashail", 'zone_id' => 3 ],
[ 'name' => "Bhuapur", 'zone_id' => 3 ],
[ 'name' => "Delduar", 'zone_id' => 3 ],
[ 'name' => "Ghatail", 'zone_id' => 3 ],
[ 'name' => "Gopalpur", 'zone_id' => 3 ],
[ 'name' => "Kalihati", 'zone_id' => 3 ],
[ 'name' => "Mirzapur", 'zone_id' => 3 ],
[ 'name' => "Modhupur", 'zone_id' => 3 ],
[ 'name' => "Nagarpur", 'zone_id' => 3 ],
[ 'name' => "Shakhipur", 'zone_id' => 3 ],
[ 'name' => "Tangail Sadar", 'zone_id' => 3 ],
[ 'name' => "Dhanbari", 'zone_id' => 3 ],
[ 'name' => "Bagerhat Sadar", 'zone_id' => 3 ],
[ 'name' => "Chitalmari", 'zone_id' => 3 ],
[ 'name' => "Fakirhat", 'zone_id' => 3 ],
[ 'name' => "Kachua", 'zone_id' => 3 ],
[ 'name' => "Mollarhat", 'zone_id' => 3 ],
[ 'name' => "Mongla", 'zone_id' => 3 ],
[ 'name' => "Morelganj", 'zone_id' => 3 ],
[ 'name' => "Rampal", 'zone_id' => 3 ],
[ 'name' => "Sarankhola", 'zone_id' => 3 ],
[ 'name' => "Alamdanga", 'zone_id' => 3 ],
[ 'name' => "Chuadanga Sadar", 'zone_id' => 3 ],
[ 'name' => "Damurhuda", 'zone_id' => 3 ],
[ 'name' => "Jibannagar", 'zone_id' => 3 ],
[ 'name' => "Noapara Noapara", 'zone_id' => 3 ],
[ 'name' => "Bagherpara", 'zone_id' => 3 ],
[ 'name' => "Chowgacha", 'zone_id' => 3 ],
[ 'name' => "Jessore Sadar", 'zone_id' => 3 ],
[ 'name' => "Jhikargacha", 'zone_id' => 3 ],
[ 'name' => "Keshabpur", 'zone_id' => 3 ],
[ 'name' => "Manirampur", 'zone_id' => 3 ],
[ 'name' => "Sharsha", 'zone_id' => 3 ],
[ 'name' => "Kotchandpur", 'zone_id' => 3 ],
[ 'name' => "Harinakunda", 'zone_id' => 3 ],
[ 'name' => "Jhenaidah Sadar", 'zone_id' => 3 ],
[ 'name' => "Moheshpur", 'zone_id' => 3 ],
[ 'name' => "Shailkupa", 'zone_id' => 3 ],
[ 'name' => "Batiaghata", 'zone_id' => 3 ],
[ 'name' => "Dacope", 'zone_id' => 3 ],
[ 'name' => "Dighalia", 'zone_id' => 3 ],
[ 'name' => "Dumuria", 'zone_id' => 3 ],
[ 'name' => "Phultala", 'zone_id' => 3 ],
[ 'name' => "Koira", 'zone_id' => 3 ],
[ 'name' => "Paikgacha", 'zone_id' => 3 ],
[ 'name' => "Rupsa", 'zone_id' => 3 ],
[ 'name' => "Khalispur", 'zone_id' => 3 ],
[ 'name' => "Sonadanga", 'zone_id' => 3 ],
[ 'name' => "Khan jahan ali ", 'zone_id' => 3 ],
[ 'name' => "Doulatpur", 'zone_id' => 3 ],
[ 'name' => "Terokhada", 'zone_id' => 3 ],
[ 'name' => "Bheramara", 'zone_id' => 3 ],
[ 'name' => "Khoksha", 'zone_id' => 3 ],
[ 'name' => "Kumarkhali", 'zone_id' => 3 ],
[ 'name' => "Kushtia Sadar", 'zone_id' => 3 ],
[ 'name' => "Magura Sadar", 'zone_id' => 3 ],
[ 'name' => "Mohammadpur", 'zone_id' => 3 ],
[ 'name' => "Shalikha", 'zone_id' => 3 ],
[ 'name' => "Gangni", 'zone_id' => 3 ],
[ 'name' => "Meherpur Sadar", 'zone_id' => 3 ],
[ 'name' => "Mujibnagar", 'zone_id' => 3 ],
[ 'name' => "Kalia", 'zone_id' => 3 ],
[ 'name' => "Lohagara", 'zone_id' => 3 ],
[ 'name' => "Narail Sadar", 'zone_id' => 3 ],
[ 'name' => "Assasuni", 'zone_id' => 3 ],
[ 'name' => "Debhata", 'zone_id' => 3 ],
[ 'name' => "Kolaroa", 'zone_id' => 3 ],
[ 'name' => "Satkhira Sadar", 'zone_id' => 3 ],
[ 'name' => "Shyamnagar", 'zone_id' => 3 ],
[ 'name' => "Tala", 'zone_id' => 3 ],
[ 'name' => "Adamdighi", 'zone_id' => 3 ],
[ 'name' => "Bogra Sadar", 'zone_id' => 3 ],
[ 'name' => "Dhunot", 'zone_id' => 3 ],
[ 'name' => "Dhubchanchia", 'zone_id' => 3 ],
[ 'name' => "Gabtali", 'zone_id' => 3 ],
[ 'name' => "Kahaloo", 'zone_id' => 3 ],
[ 'name' => "Nandigram", 'zone_id' => 3 ],
[ 'name' => "Sariakandi", 'zone_id' => 3 ],
[ 'name' => "Sherpur", 'zone_id' => 3 ],
[ 'name' => "Shibganj", 'zone_id' => 3 ],
[ 'name' => "Sonatola", 'zone_id' => 3 ],
[ 'name' => "Shajahanpur", 'zone_id' => 3 ],
[ 'name' => "Bholahat", 'zone_id' => 3 ],
[ 'name' => "Gomastapur", 'zone_id' => 3 ],
[ 'name' => "Nachole", 'zone_id' => 3 ],
[ 'name' => "Nawabganj Sadar", 'zone_id' => 3 ],
[ 'name' => "Shipganj", 'zone_id' => 3 ],
[ 'name' => "Akkelpur", 'zone_id' => 3 ],
[ 'name' => "Joypurhat Sadar", 'zone_id' => 3 ],
[ 'name' => "Kalai", 'zone_id' => 3 ],
[ 'name' => "Khetlal", 'zone_id' => 3 ],
[ 'name' => "Panchbibi", 'zone_id' => 3 ],
[ 'name' => "Atrai", 'zone_id' => 3 ],
[ 'name' => "Badalgachi", 'zone_id' => 3 ],
[ 'name' => "Dhamoirhat", 'zone_id' => 3 ],
[ 'name' => "Manda", 'zone_id' => 3 ],
[ 'name' => "Mahadebpur", 'zone_id' => 3 ],
[ 'name' => "Naogaon Sadar", 'zone_id' => 3 ],
[ 'name' => "Niamatpur", 'zone_id' => 3 ],
[ 'name' => "Patnitala", 'zone_id' => 3 ],
[ 'name' => "Porsha", 'zone_id' => 3 ],
[ 'name' => "Raninagar", 'zone_id' => 3 ],
[ 'name' => "Shapahar", 'zone_id' => 3 ],
[ 'name' => "Baghatipara", 'zone_id' => 3 ],
[ 'name' => "Baraigram", 'zone_id' => 3 ],
[ 'name' => "Gurudaspur", 'zone_id' => 3 ],
[ 'name' => "Lalpur", 'zone_id' => 3 ],
[ 'name' => "Natore Sadar", 'zone_id' => 3 ],
[ 'name' => "Singra", 'zone_id' => 3 ],
[ 'name' => "Atgharia", 'zone_id' => 3 ],
[ 'name' => "Bera", 'zone_id' => 3 ],
[ 'name' => "Bhangura", 'zone_id' => 3 ],
[ 'name' => "Chatmohar", 'zone_id' => 3 ],
[ 'name' => "Faridpur", 'zone_id' => 3 ],
[ 'name' => "Iswardi", 'zone_id' => 3 ],
[ 'name' => "Pabna Sadar", 'zone_id' => 3 ],
[ 'name' => "Santhia", 'zone_id' => 3 ],
[ 'name' => "Sujanagar", 'zone_id' => 3 ],
[ 'name' => "Bagha", 'zone_id' => 3 ],
[ 'name' => "Bagmara", 'zone_id' => 3 ],
[ 'name' => "Charghat", 'zone_id' => 3 ],
[ 'name' => "Godagari", 'zone_id' => 3 ],
[ 'name' => "Mohanpur", 'zone_id' => 3 ],
[ 'name' => "Paba", 'zone_id' => 3 ],
[ 'name' => "Putia", 'zone_id' => 3 ],
[ 'name' => "Tanore", 'zone_id' => 3 ],
[ 'name' => "Sadar", 'zone_id' => 3 ],
[ 'name' => "Belkuchi", 'zone_id' => 3 ],
[ 'name' => "Chowhali", 'zone_id' => 3 ],
[ 'name' => "Kamarkhanda", 'zone_id' => 3 ],
[ 'name' => "Kazipur", 'zone_id' => 3 ],
[ 'name' => "Raiganj", 'zone_id' => 3 ],
[ 'name' => "Shahajadpur", 'zone_id' => 3 ],
[ 'name' => "Sirajganj Sadar", 'zone_id' => 3 ],
[ 'name' => "Tarash", 'zone_id' => 3 ],
[ 'name' => "Ullapara", 'zone_id' => 3 ],
[ 'name' => "Ajmeriganj", 'zone_id' => 3 ],
[ 'name' => "Bahubal", 'zone_id' => 3 ],
[ 'name' => "Baniachang", 'zone_id' => 3 ],
[ 'name' => "Chunarughat", 'zone_id' => 3 ],
[ 'name' => "Habiganj Sadar", 'zone_id' => 3 ],
[ 'name' => "Lakhai", 'zone_id' => 3 ],
[ 'name' => "Madhabpur", 'zone_id' => 3 ],
[ 'name' => "Nabiganj", 'zone_id' => 3 ],
[ 'name' => "Barlekha", 'zone_id' => 3 ],
[ 'name' => "Kamalganj", 'zone_id' => 3 ],
[ 'name' => "Kulaura", 'zone_id' => 3 ],
[ 'name' => "Moulvibazar Sadar", 'zone_id' => 3 ],
[ 'name' => "Rajnagar", 'zone_id' => 3 ],
[ 'name' => "Sreemongal", 'zone_id' => 3 ],
[ 'name' => "Juri", 'zone_id' => 3 ],
[ 'name' => "Biswambharpur", 'zone_id' => 3 ],
[ 'name' => "Chattak", 'zone_id' => 3 ],
[ 'name' => "Derai", 'zone_id' => 3 ],
[ 'name' => "Dharmapasha", 'zone_id' => 3 ],
[ 'name' => "Dowarabazar", 'zone_id' => 3 ],
[ 'name' => "Jagannathpur", 'zone_id' => 3 ],
[ 'name' => "Jamalganj", 'zone_id' => 3 ],
[ 'name' => "Sulla", 'zone_id' => 3 ],
[ 'name' => "Sunamganj Sadar", 'zone_id' => 3 ],
[ 'name' => "Taherpur", 'zone_id' => 3 ],
[ 'name' => "South Sunamganj", 'zone_id' => 3 ],
[ 'name' => "Balaganj", 'zone_id' => 3 ],
[ 'name' => "Beanibazar", 'zone_id' => 3 ],
[ 'name' => "Biswanath", 'zone_id' => 3 ],
[ 'name' => "Companyganj", 'zone_id' => 3 ],
[ 'name' => "Fenchuganj", 'zone_id' => 3 ],
[ 'name' => "Gowainghat", 'zone_id' => 3 ],
[ 'name' => "Golapganj", 'zone_id' => 3 ],
[ 'name' => "Jaintapur", 'zone_id' => 3 ],
[ 'name' => "Zakiganj", 'zone_id' => 3 ],
[ 'name' => "Kanaighat", 'zone_id' => 3 ],
[ 'name' => "Sylhet Sadar", 'zone_id' => 3 ],
[ 'name' => "South Surma", 'zone_id' => 3 ],
[ 'name' => "Amtali", 'zone_id' => 3 ],
[ 'name' => "Bamna", 'zone_id' => 3 ],
[ 'name' => "Barguna Sadar", 'zone_id' => 3 ],
[ 'name' => "Betagi", 'zone_id' => 3 ],
[ 'name' => "Patharghata", 'zone_id' => 3 ],
[ 'name' => "Agailjhara", 'zone_id' => 3 ],
[ 'name' => "Babuganj", 'zone_id' => 3 ],
[ 'name' => "Bakerganj", 'zone_id' => 3 ],
[ 'name' => "Banaripara", 'zone_id' => 3 ],
[ 'name' => "Barisal Sadar", 'zone_id' => 3 ],
[ 'name' => "Gournadi", 'zone_id' => 3 ],
[ 'name' => "Hijla", 'zone_id' => 3 ],
[ 'name' => "Mehendiganj", 'zone_id' => 3 ],
[ 'name' => "Muladi", 'zone_id' => 3 ],
[ 'name' => "Wazirpur", 'zone_id' => 3 ],
[ 'name' => "Bhola Sadar", 'zone_id' => 3 ],
[ 'name' => "Borhanuddin", 'zone_id' => 3 ],
[ 'name' => "Charfession", 'zone_id' => 3 ],
[ 'name' => "Daulatkhan", 'zone_id' => 3 ],
[ 'name' => "Lalmohan", 'zone_id' => 3 ],
[ 'name' => "Manpura", 'zone_id' => 3 ],
[ 'name' => "Tajumuddin", 'zone_id' => 3 ],
[ 'name' => "Jhalokathi Sadar", 'zone_id' => 3 ],
[ 'name' => "Kathalia", 'zone_id' => 3 ],
[ 'name' => "Nalchiti", 'zone_id' => 3 ],
[ 'name' => "Rajapur", 'zone_id' => 3 ],
[ 'name' => "Bauphal", 'zone_id' => 3 ],
[ 'name' => "Dasmina", 'zone_id' => 3 ],
[ 'name' => "Dumki", 'zone_id' => 3 ],
[ 'name' => "Galachipa", 'zone_id' => 3 ],
[ 'name' => "Kalapara", 'zone_id' => 3 ],
[ 'name' => "Mirjaganj", 'zone_id' => 3 ],
[ 'name' => "Patuakhali Sadar", 'zone_id' => 3 ],
[ 'name' => "Bhandaria", 'zone_id' => 3 ],
[ 'name' => "Kaukhali", 'zone_id' => 3 ],
[ 'name' => "Mothbaria", 'zone_id' => 3 ],
[ 'name' => "Nesarabad (Shawrupkathi)", 'zone_id' => 3 ],
[ 'name' => "Nazirpur", 'zone_id' => 3 ],
[ 'name' => "Perojpur Sadar", 'zone_id' => 3 ],
[ 'name' => "Zia Nagar (Indurkani)", 'zone_id' => 3 ],
[ 'name' => "Ali Kadam", 'zone_id' => 3 ],
[ 'name' => "Bandarban Sadar", 'zone_id' => 3 ],
[ 'name' => "Lama", 'zone_id' => 3 ],
[ 'name' => "Nakhoyngchari", 'zone_id' => 3 ],
[ 'name' => "Rawanchari", 'zone_id' => 3 ],
[ 'name' => "Ruma", 'zone_id' => 3 ],
[ 'name' => "Thanchi", 'zone_id' => 3 ],
[ 'name' => "Akhaura", 'zone_id' => 3 ],
[ 'name' => "Ashuganj", 'zone_id' => 3 ],
[ 'name' => "Bancharampur", 'zone_id' => 3 ],
[ 'name' => "Brahmanbaria Sadar", 'zone_id' => 3 ],
[ 'name' => "Kashba", 'zone_id' => 3 ],
[ 'name' => "Nabinagar", 'zone_id' => 3 ],
[ 'name' => "Nasirnagar", 'zone_id' => 3 ],
[ 'name' => "Sarail", 'zone_id' => 3 ],
[ 'name' => "Chandpur Sadar", 'zone_id' => 3 ],
[ 'name' => "Faridganj", 'zone_id' => 3 ],
[ 'name' => "Haimchar", 'zone_id' => 3 ],
[ 'name' => "Hajiganj", 'zone_id' => 3 ],
[ 'name' => "Matlab (South)", 'zone_id' => 3 ],
[ 'name' => "Matlab (North)(Chengarchar)", 'zone_id' => 3 ],
[ 'name' => "Shahrasti", 'zone_id' => 3 ],
[ 'name' => "Anwara", 'zone_id' => 3 ],
[ 'name' => "Banshkhali", 'zone_id' => 3 ],
[ 'name' => "Boalkhali", 'zone_id' => 3 ],
[ 'name' => "Chandanaish", 'zone_id' => 3 ],
[ 'name' => "Fatikchari", 'zone_id' => 3 ],
[ 'name' => "Hathazari", 'zone_id' => 3 ],
[ 'name' => "Mirsarai", 'zone_id' => 3 ],
[ 'name' => "Patiya", 'zone_id' => 3 ],
[ 'name' => "Rangunia", 'zone_id' => 3 ],
[ 'name' => "Raujan", 'zone_id' => 3 ],
[ 'name' => "Sandwip", 'zone_id' => 3 ],
[ 'name' => "Satkania", 'zone_id' => 3 ],
[ 'name' => "Sitakundu", 'zone_id' => 3 ],
[ 'name' => "Barura", 'zone_id' => 3 ],
[ 'name' => "Brahmanpara", 'zone_id' => 3 ],
[ 'name' => "Burichang", 'zone_id' => 3 ],
[ 'name' => "Chandina", 'zone_id' => 3 ],
[ 'name' => "Chowddagram", 'zone_id' => 3 ],
[ 'name' => "Comilla Sadar", 'zone_id' => 3 ],
[ 'name' => "Daudkandi", 'zone_id' => 3 ],
[ 'name' => "Debiduar", 'zone_id' => 3 ],
[ 'name' => "Homna", 'zone_id' => 3 ],
[ 'name' => "Laksam", 'zone_id' => 3 ],
[ 'name' => "Meghna", 'zone_id' => 3 ],
[ 'name' => "Muradnagar", 'zone_id' => 3 ],
[ 'name' => "Nangolkot", 'zone_id' => 3 ],
[ 'name' => "Titas", 'zone_id' => 3 ],
[ 'name' => "Monoharganj", 'zone_id' => 3 ],
[ 'name' => "Comilla Sadar South", 'zone_id' => 3 ],
[ 'name' => "Chakoria", 'zone_id' => 3 ],
[ 'name' => "Cox's Bazar Sadar", 'zone_id' => 3 ],
[ 'name' => "Kutubdia", 'zone_id' => 3 ],
[ 'name' => "Moheshkhali", 'zone_id' => 3 ],
[ 'name' => "Pekua", 'zone_id' => 3 ],
[ 'name' => "Ramu", 'zone_id' => 3 ],
[ 'name' => "Teknaf", 'zone_id' => 3 ],
[ 'name' => "Ukhia", 'zone_id' => 3 ],
[ 'name' => "Chagalnayya", 'zone_id' => 3 ],
[ 'name' => "Daganbhuiyan", 'zone_id' => 3 ],
[ 'name' => "Feni Sadar", 'zone_id' => 3 ],
[ 'name' => "Parshuram", 'zone_id' => 3 ],
[ 'name' => "Fulgazi", 'zone_id' => 3 ],
[ 'name' => "Sonagazi", 'zone_id' => 3 ],
[ 'name' => "Dighinala", 'zone_id' => 3 ],
[ 'name' => "Khagrachari Sadar", 'zone_id' => 3 ],
[ 'name' => "Laksmichari", 'zone_id' => 3 ],
[ 'name' => "Mohalchari", 'zone_id' => 3 ],
[ 'name' => "Manikchari", 'zone_id' => 3 ],
[ 'name' => "Matiranga", 'zone_id' => 3 ],
[ 'name' => "Panchari", 'zone_id' => 3 ],
[ 'name' => "Ramgor", 'zone_id' => 3 ],
[ 'name' => "Laksmipur Sadar", 'zone_id' => 3 ],
[ 'name' => "Ramgati", 'zone_id' => 3 ],
[ 'name' => "Ramganj", 'zone_id' => 3 ],
[ 'name' => "Raipur", 'zone_id' => 3 ],
[ 'name' => "Kamalnagar", 'zone_id' => 3 ],
[ 'name' => "Begumganj", 'zone_id' => 3 ],
[ 'name' => "Chatkhil", 'zone_id' => 3 ],
[ 'name' => "Companiganj", 'zone_id' => 3 ],
[ 'name' => "Hatiya", 'zone_id' => 3 ],
[ 'name' => "Noakhali Sadar(Sudharam)", 'zone_id' => 3 ],
[ 'name' => "Senbag", 'zone_id' => 3 ],
[ 'name' => "Sonaimuri", 'zone_id' => 3 ],
[ 'name' => "Subarnachar", 'zone_id' => 3 ],
[ 'name' => "Kabir Hat", 'zone_id' => 3 ],
[ 'name' => "Baghaichari", 'zone_id' => 3 ],
[ 'name' => "Barkal", 'zone_id' => 3 ],
[ 'name' => "Belaichari", 'zone_id' => 3 ],
[ 'name' => "Jurachari", 'zone_id' => 3 ],
[ 'name' => "Kaptai", 'zone_id' => 3 ],
[ 'name' => "Kawkhali", 'zone_id' => 3 ],
[ 'name' => "Langadu", 'zone_id' => 3 ],
[ 'name' => "Naniarchar", 'zone_id' => 3 ],
[ 'name' => "Rajasthali", 'zone_id' => 3 ],
[ 'name' => "Rangamati Sadar", 'zone_id' => 3 ],
[ 'name' => "Birampur", 'zone_id' => 3 ],
[ 'name' => "Birganj", 'zone_id' => 3 ],
[ 'name' => "Birol", 'zone_id' => 3 ],
[ 'name' => "Bochaganj", 'zone_id' => 3 ],
[ 'name' => "Chirirbandar", 'zone_id' => 3 ],
[ 'name' => "Dinajpur Sadar", 'zone_id' => 3 ],
[ 'name' => "Phulbari", 'zone_id' => 3 ],
[ 'name' => "Ghoraghat", 'zone_id' => 3 ],
[ 'name' => "Hakimpur", 'zone_id' => 3 ],
[ 'name' => "Kaharole", 'zone_id' => 3 ],
[ 'name' => "Khanshama", 'zone_id' => 3 ],
[ 'name' => "Nawabganj", 'zone_id' => 3 ],
[ 'name' => "Parbatipur", 'zone_id' => 3 ],
[ 'name' => "Fulchari", 'zone_id' => 3 ],
[ 'name' => "Gaibandha Sadar", 'zone_id' => 3 ],
[ 'name' => "Gobindaganj", 'zone_id' => 3 ],
[ 'name' => "Palashbari", 'zone_id' => 3 ],
[ 'name' => "Sadullapur", 'zone_id' => 3 ],
[ 'name' => "Shaghatta", 'zone_id' => 3 ],
[ 'name' => "Sundarganj", 'zone_id' => 3 ],
[ 'name' => "Bhurungamari", 'zone_id' => 3 ],
[ 'name' => "Chilmary", 'zone_id' => 3 ],
[ 'name' => "Fulbari", 'zone_id' => 3 ],
[ 'name' => "Kurigram Sadar", 'zone_id' => 3 ],
[ 'name' => "Nageswari", 'zone_id' => 3 ],
[ 'name' => "Rajarhat", 'zone_id' => 3 ],
[ 'name' => "Rajibpur", 'zone_id' => 3 ],
[ 'name' => "Rowmari", 'zone_id' => 3 ],
[ 'name' => "Ulipur", 'zone_id' => 3 ],
[ 'name' => "Aditmari", 'zone_id' => 3 ],
[ 'name' => "Hatibandha", 'zone_id' => 3 ],
[ 'name' => "Lalmonirhat Sadar", 'zone_id' => 3 ],
[ 'name' => "Patgram", 'zone_id' => 3 ],
[ 'name' => "Dimla", 'zone_id' => 3 ],
[ 'name' => "Domar", 'zone_id' => 3 ],
[ 'name' => "Jaldhaka", 'zone_id' => 3 ],
[ 'name' => "Kishoreganj", 'zone_id' => 3 ],
[ 'name' => "Nilphamari Sadar", 'zone_id' => 3 ],
[ 'name' => "Saidpur", 'zone_id' => 3 ],
[ 'name' => "Atwari", 'zone_id' => 3 ],
[ 'name' => "Boda", 'zone_id' => 3 ],
[ 'name' => "Debiganj", 'zone_id' => 3 ],
[ 'name' => "Panchagarh Sadar", 'zone_id' => 3 ],
[ 'name' => "Tetulia", 'zone_id' => 3 ],
[ 'name' => "Badarganj", 'zone_id' => 3 ],
[ 'name' => "Gangachara", 'zone_id' => 3 ],
[ 'name' => "Kaunia", 'zone_id' => 3 ],
[ 'name' => "Mithapukur", 'zone_id' => 3 ],
[ 'name' => "Pirgacha", 'zone_id' => 3 ],
[ 'name' => "Pirganj", 'zone_id' => 3 ],
[ 'name' => "Rangpur Sadar", 'zone_id' => 3 ],
[ 'name' => "Taraganj", 'zone_id' => 3 ],
[ 'name' => "Baliadangi", 'zone_id' => 3 ],
[ 'name' => "Haripur", 'zone_id' => 3 ],
[ 'name' => "Ranishankail", 'zone_id' => 3 ],
[ 'name' => "Thakurgaon Sadar", 'zone_id' => 3 ],
[ 'name' => "Khulna Sadar", 'zone_id' => 3 ],
[ 'name' => "Rajshahi Shadar", 'zone_id' => 3 ],
[ 'name' => "Chittagong Sadar", 'zone_id' => 3 ],
[ 'name' => "Chapai Nawabganj Sadar চাঁপাইনবাবগঞ্জ সদর", 'zone_id' => 3 ],
[ 'name' => "Benapole", 'zone_id' => 3 ],


        ]);
    }
}
